<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">尊敬的</span><span style="mso-spacerun:'yes';color:#ff0000;text-decoration:underline;font-style:italic;font-size:12.0000pt;font-family:'宋体';">${realName}</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">用户，您好</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">非常高兴地通知您，您的订单号为&nbsp;</span><span style="mso-spacerun:'yes';text-decoration:underline;font-style:italic;font-size:12.0000pt;font-family:'宋体';">${orderNo}</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;的订单喜中奖<span style="font-family:宋体;">，奖金</span><span style="font-family:Calibri;">${winMoney}</span><span style="font-family:宋体;">元！再次恭喜您！</span></span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">订单详情如下：</span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;${orderDetail}</span></p>

<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:宋体;">开奖情况如下：</span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;${lotteryDetail}</span></p>

<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">查阅更多开奖信息</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">，</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">点击</span><a href="http://www.yicp.com/actkaijiang/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://www.yicp.com/actkaijiang/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">关注壹彩微信，开奖早知道。</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p16" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><img width="181" height="195" src="file:///C:\Users\ADMINI~1\AppData\Local\Temp\ksohtml\wpsC126.tmp.png" /><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">实时查阅开奖信息</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">，</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">点击</span><a href="http://www.yicp.com/actkaijiang/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://www.yicp.com/actkaijiang/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">分析走势图表，点击</span><a href="http://chart.yicp.com/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://chart.yicp.com/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;300<span style="font-family:宋体;">张超大数据分析表，大奖离你更近。</span></span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">丰富彩票资讯，把握实时彩票动态</span><a href="http://www.yicp.com/actinfo/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://www.yicp.com/actinfo/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">一彩票&nbsp;</span><a href="http://www.yicp.com/"><span class="15" style="color:#0563c1;font-family:宋体;">http://www.yicp.com</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;祝您好运！</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">客服电话：<span style="font-family:Calibri;">020-6286&nbsp;6286&nbsp;</span><span style="font-family:宋体;">，客服邮箱：</span></span><a href="mailto:crm@yicp.com"><span class="15" style="color:#0563c1;font-family:宋体;">crm@yicp.com</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;，在线<span style="font-family:Calibri;">QQ</span><span style="font-family:宋体;">：</span></span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">1059686600</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>