function changeChartInfo(football,ltype,tt,chartType)
{
	
	  if(chartType=="plt")
	  {
	   if(tt=="js")
	    $("#chart_intro").html("频率图显示在某一段时间内，每期中奖号码中奇数的个数与所出现的期数，例如：最近10期，中奖号码中有3个数字为奇数的期数有5期");
	   if(tt=="haoma")
	    $("#chart_intro").html("频率图统计在某一段时间内，所有号码所出现的次数");
	   if(tt=="zds")
	    $("#chart_intro").html("统计在某一段时间内，中奖号码中最大的数字所出现的次数");
	   if(tt=="zxs")
	    $("#chart_intro").html("统计在某一段时间内，中奖号码中最小的数字所出现的次数");
	   if(tt=="lh")
	    $("#chart_intro").html("连号频率统计主要统计在一段时间内，最大连号个数为特定数目的期数，例如从2003001期到2003038期最大连号个数为3的期数有几期");
	   if(tt=="yanxu")
	    $("#chart_intro").html("延续数目是指本期号码与上一期号码相同号码的个数，延续频率统计即指在一段时间内延续数目为特定数目的期数为几期");
	   if(tt=="sumNum")
	    $("#chart_intro").html("统计在某一段时间内，每期中奖号码的和值所出现的期数");
	   if(tt=="qj1")
	    $("#chart_intro").html("区间频率统计将所有33个号码划分为4个区间，1-9，10-19，20-29，30以上，并统计在一段时间内1-9区间所出现号码的个数");
	   if(tt=="qj2")
	    $("#chart_intro").html("区间频率统计将所有33个号码划分为4个区间，1-9，10-19，20-29，30以上，并统计在一段时间内10-19区间所出现号码的个数");
	   if(tt=="qj3")
	    $("#chart_intro").html("区间频率统计将所有33个号码划分为4个区间，1-9，10-19，20-29，30以上，并统计在一段时间内20-29区间所出现号码的个数");
	   if(tt=="qj4")
	    $("#chart_intro").html("区间频率统计将所有33个号码划分为4个区间，1-9，10-19，20-29，30以上，并统计在一段时间内30以上区间所出现号码的个数");
	  }

	  if(chartType=="zst")
	  {
	   if(tt=="js")
	    $("#chart_intro").html("通过该图表，可生动的显示奇数参数在最近的波动状况。")
	   if(tt=="zds")
	    $("#chart_intro").html("通过该图表，可生动的显示最大数参数在最近的波动状况。")
	   if(tt=="zxs")
	    $("#chart_intro").html("通过该图表，可生动的显示最小数参数在最近的波动状况。")
	   if(tt=="lh")
	    $("#chart_intro").html("通过该图表，可生动的显示连号参数在最近的波动状况。")
	   if(tt=="yanxu")
	    $("#chart_intro").html("延续即与上期相同号码的个数，通过该图表可显示一段时间与上期号码相同个数的走势。")
	   if(tt=="qj1")
	    $("#chart_intro").html("通过该图表，可生动的显示1区参数在最近的波动状况。")
	   if(tt=="qj2")
	    $("#chart_intro").html("通过该图表，可生动的显示2区参数在最近的波动状况。")
	   if(tt=="qj3")
	    $("#chart_intro").html("通过该图表，可生动的显示3区参数在最近的波动状况。")
	   if(tt=="qj4")
	    $("#chart_intro").html("通过该图表，可生动的显示4区参数在最近的波动状况。")
	   if(tt=="sumNum")
	    $("#chart_intro").html("通过该图表，可生动的显示和数参数在最近的波动状况。");
	  }

	  if(chartType=="fbt")
	  {
	   if(ltype=="ssq")
	    $("#chart_intro").html("左边一栏是期号，右面高亮显示红球和蓝球的中奖号码")
	   if(ltype=="qlc")
	    $("#chart_intro").html("左边一栏显示期号，右边分五栏分别显示相应位的中奖号码，每位中奖号码用不同的颜色显示")
	   if(ltype=="qxc")
	   $("#chart_intro").html("左边一栏显示期号，右边分五栏分别显示相应位的中奖号码，每位中奖号码用不同的颜色显示")
	   if(ltype=="pls")
	    $("#chart_intro").html("左边一栏显示期号，右边分三栏分别显示相应位的中奖号码，每位中奖号码用不同的颜色显示")
	   if(ltype=="plw")
	    $("#chart_intro").html("左边一栏显示期号，右边分五栏分别显示相应位的中奖号码，每位中奖号码用不同的颜色显示")
	   if(ltype=="dlt")
	    $("#chart_intro").html("左边一栏是期号，右面高亮显示红球和蓝球的中奖号码")
	   if(ltype=="3d")
	    $("#chart_intro").html("左边一栏显示期号，右边分三栏分别显示中奖号码，每个中奖号码用不同的颜色显示")
	  }
      if(football=="football"){
        if(chartType=="zst"){
        if(tt=="cc")
        $("#chart_intro").html("通过该图表，可生动的显示比赛胜平负参数在最近的波动状况。")
        if(tt=="lianxue")
        $("#chart_intro").html("通过该图表，可生动的显示连续参数在最近的波动状况。")
        if(tt=="jifen")
        $("#chart_intro").html("通过该图表，可生动的显示积分参数在最近的波动状况。")
        if(tt=="duandian")
        $("#chart_intro").html("通过该图表，可生动的显示断点参数在最近的波动状况。")
        }
        if(chartType=="plt"){
        if(tt=="cc")
        $("#chart_intro").html("连号频率统计主要统计在一段时间内，比赛胜平负所出现的次数。")
        if(tt=="lianxue")
        $("#chart_intro").html("连号频率统计主要统计在一段时间内，比赛胜平负连续所出现的次数。")
        if(tt=="duandian")
        $("#chart_intro").html("连号频率统计主要统计在一段时间内，比赛胜平负断点所出现的次数")
        }
      }
}

