<p class="p15" style="margin-left:18.0000pt;margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">尊敬的</span><span style="mso-spacerun:'yes';color:#ff0000;text-decoration:underline;font-style:italic;font-size:12.0000pt;font-family:'宋体';">${realName}</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">用户，您好</span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">非常感谢您成为我们一彩票的会员，您</span><span style="font-size:12pt;"><span style="font-family:Calibri;">于<span style="color:#e53333;">${time}</span></span></span><span style="font-size:12pt;"><span style="font-family:Calibri;">发起了</span></span><span style="font-size:12pt;"><span style="font-family:Calibri;"><span style="font-size:12pt;"><span style="font-family:Calibri;color:#e53333;">${money}</span></span><span style="font-size:12pt;"><span style="font-family:Calibri;">元的提款申请</span><span style="font-family:宋体;">。明细如下：</span></span><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></span></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><span style="font-family:宋体;">${detail}</span></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">更详细消费记录，参阅</span><a href="http://www.yicp.com/customer/customerUseDetail.html"><span class="15" style="color:#0563c1;font-size:12pt;font-family:'Times New Roman';">http://www.yicp.com/customer/customerUseDetail.html</span></a><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:12.0000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">实时查阅开奖信息</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">，</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">点击</span><a href="http://www.yicp.com/actkaijiang/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://www.yicp.com/actkaijiang/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">分析走势图表，点击</span><a href="http://chart.yicp.com/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://chart.yicp.com/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;300<span style="font-family:宋体;">张超大数据分析表，大奖离你更近。</span></span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">丰富彩票资讯，把握实时彩票动态</span><a href="http://www.yicp.com/actinfo/"><span class="15" style="color:#0563c1;font-family:'Times New Roman';">http://www.yicp.com/actinfo/</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">一彩票&nbsp;</span><a href="http://www.yicp.com/"><span class="15" style="color:#0563c1;font-family:宋体;">http://www.yicp.com</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;祝您好运！</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span></p>
<p class="p0" style="margin-top:0pt;margin-bottom:0pt;"><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">客服电话：<span style="font-family:Calibri;">020-6286&nbsp;6286&nbsp;</span><span style="font-family:宋体;">，客服邮箱：</span></span><a href="mailto:crm@yicp.com"><span class="15" style="color:#0563c1;font-family:宋体;">crm@yicp.com</span></a><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;，在线<span style="font-family:Calibri;">QQ</span><span style="font-family:宋体;">：</span></span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'Calibri';">1059686600</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';">&nbsp;</span><span style="mso-spacerun:'yes';font-size:10.5000pt;font-family:'宋体';"><o:p></o:p></span></p>